### ISSUE TITLE
CI does not check Cargo.lock consistency

### ISSUE THREAD

**Issue by MOZGIII** [iTrooz/efivar-rs#81]
See title, and `Cargo.lock` is not up to date, and gets dirty on `cargo check`

**Comment by iTrooz** [comment]
Not sure what you mean, I just ran `cargo check` and `Cargo.lock` didn't change
And how would you go about checking its consistency in the CI ?

**Comment by MOZGIII** [comment]
It did for me, super odd.

But you should still all the relevant flags to CI: `--frozen-lockfile` I beleive it is

**Comment by MOZGIII** [comment]
[diff.patch](https://github.com/iTrooz/efivar-rs/files/15053267/diff.patch)

**Comment by iTrooz** [comment]
Sorry for the delay, I'm was busy, I'll try to reply quicker now

`--frozen-lockfile` doesn't exist, but `--frozen` exists which seems similar. I just added it to the CI, but as you can see, the CI still pass. Not sure where you are getting your diffs from

**Comment by iTrooz** [comment]
Please ignore my last (now deleted) message

I found out why I didn't get the diffs: I wasn't using the latest commits (more specifically I didn't pull https://github.com/iTrooz/efivar-rs/commit/2a9e699ee22af1c71a870331e75722f363550b33)

I added the `--frozen` flag to the CI, and fixed Cargo.lock. Everything should work fine now.

Thanks for reporting this !

**Comment by iTrooz** [comment]
https://github.com/iTrooz/efivar-rs/commit/d63ed605bc66d2aab9c3dcb26b06f904dbb43249#commitcomment-141447546
